{% set name = "interleave" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cdc1462acad1f5d5643aa4e9c5fffa7ea874c0777f40c95cfc2a750a5065ad2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-rerunfailures >=10
  source_files:
    - test
    - tox.ini
  imports:
    - interleave
  commands:
    - python -m pytest -vv -k "not test_ctrl_c" test

about:
  home: https://github.com/jwodder/interleave
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Yield from multiple iterators as values become available
  description: |
    The `interleave` package provides a function of the same name that takes a
    number of iterators, runs them in separate threads, and yields the values
    produced as soon as each one is available.
  dev_url: https://github.com/jwodder/interleave

extra:
  recipe-maintainers:
    - jwodder
