{% set name = "interleave" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c4595e05c5c3286d306db7459972bada9a38088fb8649c1199782c8e4a60a32

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-rerunfailures >=10
    - python {{ python_min }}
  source_files:
    - test
    - tox.ini
  imports:
    - interleave
  commands:
    - python -m pytest -vv -k "not test_ctrl_c" test

about:
  home: https://github.com/jwodder/interleave
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Yield from multiple iterators as values become available
  description: |
    The `interleave` package provides a function of the same name that takes a
    number of iterators, runs them in separate threads, and yields the values
    produced as soon as each one is available.
  dev_url: https://github.com/jwodder/interleave

extra:
  recipe-maintainers:
    - jwodder
